### PR TITLE
Add custom time format in Calendar events

### LINKED ISSUE #210: Custom Time Format not working in Calendar events
Hello,
I wanted to file in a minor bug.

When specifying a different time format (e.g. 24h), both under `settings.py` and under Calendar Customizations, the events are still shown in 12h format in the calendar (1:15-2:00 vs the left axis in example below).
Maybe we need to add [`timeFormat`](https://fullcalendar.io/docs/v3/timeFormat) somewhere in [NEMO/templates/calendar/calendar.html](https://github.com/usnistgov/NEMO/blob/master/NEMO/templates/calendar/calendar.html)?
Thanks in advance

image 
image

### PR DESCRIPTION
**Pull request by r-xyz**
Add custom time format in Calendar events.

Closes #210

### CODE REVIEW

**Comment by r-xyz** [comment]
Initial draft using 3 additional variables.

Configuration looks like this:
image

I am wondering if the labels on the left on the configuration input box can be made clearer. It could be either using  a more visual style like`Day view - Column format`/`Day view - Time format` or grouping them by view (not sure if we can add separators).

PS: one note on monthly view. Previous default format was hiding minutes when equal to `0`, but I could not find that option in [FullCalendar documentation](https://fullcalendar.io/docs/v1/formatDate).

**Comment by rptmat57** [comment]
looks like the time format for months is `h(:mm)t` https://fullcalendar.io/docs/v3/timeFormat
It looks good. I would suggest adding a migration for the customization name change so people don't have to set it up again.
If it's too much trouble I can also add it myself

**Comment by r-xyz** [comment]
Corrected the default in month view and added migration. Not sure if I should also add reverse migration in that case.

**Comment by rptmat57** [comment]
it would be great if you could add the reverse migration, I have been getting into the habit of adding them lately.
As NEMO's codebase is getting bigger and more complex, things could happen where we'd need to revert migrations

**Comment by r-xyz** [comment]
Thanks, suggestions included. :)

**Comment by rptmat57** [comment]
Perfect, thank you very much!

**Pull request merged**
