### PR TITLE
Page title customizations

### LINKED ISSUE #174: Landing page link naming consistency
When changing the name of landing page links under Detailed Administration (e.g., changing "Calendar" to "Reservations"), it changes the name on the large icon, but it does not change the corresponding name on the Calendar link on the top toolbar that links to the same place.  Can these be brought into consistency, so that if the name changes in one place it also changes in the other?  The same thing applies to "Tool control," "Status dashboard," and "Safety" links located both in the top toolbar and as large icons.  Thanks.

### PR DESCRIPTION
**Pull request by abuckles-uci**
This resolves #174. It allows for the "Calendar", "Tool control", "Status dashboard", "Requests", and "Safety" navbar links display text to be customized.

Is the way I saved the customizations correct? It works locally for me. Also, is the organization of the customizations acceptable?

image

### CODE REVIEW

**Comment by rptmat57** [comment]
Hi, I would prefer to have all the navbar customizations in the "Application" customization.
Maybe in a "Navbar" subsection (separated by a line in the page)?

**Comment by rptmat57** [comment]
I would also look in each template file, for example in `status_dashboard.html` and change the name in the `title` block and in the `<h1>` element

**Comment by rptmat57** [comment]
other than that it looks great, thank you for working on this!

**Comment by abuckles-uci** [comment]
> oh and one last thing, if you could rename all the navbar settings to `navbar_*` that'd be great, i.e. `navbar_calendar_text`, `navbar_tool_control_text` etc. this way it will be consistent with the navbar subsection name

Oops just saw this. I renamed them to `*_page_title` since it includes more than just navbar changes. Let me know what you think. I can make it `page_title_*` instead if you think that's better.

**Comment by abuckles-uci** [comment]
Now on the "Application" tab

image

**Comment by rptmat57** [comment]
I just deleted my comment, I like what you did. I am going to do one last code review tonight but this looks great!
Thank you!!

**Comment by abuckles-uci** [comment]
> I just deleted my comment, I like what you did. I am going to do one last code review tonight but this looks great! Thank you!!

Ok cool, thanks!

**Pull request merged**
