### PR TITLE
[Feature/change request] See by default who reported task and when #176

### LINKED ISSUE #176: [Feature/change request] See by default who reported task and when
Users are requesting that the timestamp and username of people reporting tool issues be visible on the tool status page without having to click the down arrow.  Specifically, they want this to be visible by default:
"This task was created by User Name (username123) on [Date] @ [Time].

Could this be added as a customization option or user preference in a future build?

### PR DESCRIPTION
**Pull request by abuckles-uci**
This closes #176 

By default the details of a task on the tool control page are hidden/collapsed. Can enable this customization to show them by default (though task details can still be collapsed by clicking on them).

image

image

### CODE REVIEW

**Comment by rptmat57** [comment]
This looks great!
Could you also add it so it works the same in the kiosk?

Thanks!
Mathieu

**Comment by abuckles-uci** [comment]
Hi Mathieu,

I made the code change for the kiosk page and was able to test by making sure the CSS classes were applied correctly. However, I haven't worked with kiosks before and wasn't able to fully test the UI. I ran into this issue even before making my code change. None of the styling is showing up and I'm getting a console error.

image

Any ideas what's going on?

Thanks,
Aaron

**Comment by rptmat57** [comment]
Hi Aaron,
Thank you!
The issue with the static files is pretty strange, especially if it's only happening on the kiosk...
I am assuming you are using runserver for dev, so just double check your `STATIC_ROOT` in `settings.py` but again if it's working on non-kiosk pages this doesn't make much sense

**Comment by abuckles-uci** [comment]
Ah I was able to figure it out! I needed to enter my badge code on `/kiosk` to authenticate first. I see that this PR works properly on the kiosk page too, so that's good

**Pull request merged**
